-- Format for overwriting define values:
--
NDefines.NDiplomacy.MAX_CLIENT_STATES = 20
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.02
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 40
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 60	
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.075
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_NONTRIBUTARY_DEV = -0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.44
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0.30
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -5.0
NDefines.NCountry.HORDE_UNITY_PER_RAZE = 0
NDefines.NCountry.LEGITIMACY_DYNASTY_CHANGE = 50
NDefines.NCountry.STRENGTHEN_GOVERNMENT_HORDE_UNITY = 2
NDefines.NCountry.HORDE_UNITY_PER_LOOT = 0
NDefines.NCountry.HORDE_UNITY_PER_RAZE = 0
NDefines.NMilitary.LOOT_DEVASTATION_IMPACT = 15
NDefines.NMilitary.LOOTED_SCALE = 2.25
NDefines.NMilitary.LOOTED_MAX = 8
NDefines.NMilitary.LOOTED_RECOVERY = 0.2
NDefines.NMilitary.NOMAD_LOOT_TRADITION = 0.02
NDefines.NMilitary.CAV_LOOT = 2
NDefines.NMilitary.INF_LOOT = 0.5