-- Format for overwriting define values:
--
NDefines.NDiplomacy.MAX_CLIENT_STATES = 10
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 0.5
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -0.5
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.02
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 40

NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 75	
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.075
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_NONTRIBUTARY_DEV = -0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.15
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0.1
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -5.0
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 25
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.075
NDefines.NDiplomacy.HRE_FOREIGN_CONTROL_PENALTY = -0.015
NDefines.NDiplomacy.HRE_HERETIC_PENALTY = 0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 0
NDefines.NDiplomacy.HRE_VOTE_OVERLORD = 100
NDefines.NDiplomacy.HRE_VOTE_TOO_SMALL = 0
NDefines.NDiplomacy.IMPERIAL_CITY_IA = 0.005

NDefines.NCountry.HORDE_UNITY_PER_RAZE = 0
NDefines.NCountry.LEGITIMACY_DYNASTY_CHANGE = 50
NDefines.NCountry.STRENGTHEN_GOVERNMENT_HORDE_UNITY = 2
NDefines.NCountry.HORDE_UNITY_PER_LOOT = 0
NDefines.NCountry.HORDE_UNITY_PER_RAZE = 0
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -25
NDefines.NCountry.SCUTAGE_TAX_FRACTION = 0.75
NDefines.NCountry.MONARCH_MIN_SKILL = 1
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4

NDefines.NMilitary.LOOT_DEVASTATION_IMPACT = 15
NDefines.NMilitary.LOOTED_SCALE = 2.5
NDefines.NMilitary.LOOTED_MAX = 6
NDefines.NMilitary.LOOTED_RECOVERY = 0.25
NDefines.NMilitary.NOMAD_LOOT_TRADITION = 0.0
NDefines.NMilitary.CAV_LOOT = 1.5
NDefines.NMilitary.INF_LOOT = 0.5
NDefines.NMilitary.BANNER_DISCIPLINE_BONUS = 0
NDefines.NMilitary.BANNER_AGE_MULTIPLIER = 0.5
NDefines.NMilitary.BANNER_REINFORCE_SPEE = -0.25
NDefines.NMilitary.BANNER_MAINTENANCE_COST = 0.15
NDefines.NMilitary.FORTRESS_COST = 1.25
NDefines.NMilitary.MERCENARY_BASE_COST = 8.00 
NDefines.NMilitary.MERCENARY_SUPPORT_LIMIT_BASE = 10
NDefines.NMilitary.MERCENARY_SUPPORT_LIMIT_FRACTION = 0.15
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 0.25
NDefines.NMilitary.SLACKEN_AP_DROP = 0.10
NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.1750
NDefines.NMilitary.MAX_MANPOWER = 15
NDefines.NMilitary.STACKWIPE_MANPOWER_RETURN_FRACTION = 0.25
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 75
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.8
NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0.15
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = -0.10
NDefines.NMilitary.INFANTRY_COST = 15
NDefines.NMilitary.CAVALRY_COST = 25
NDefines.NMilitary.ARTILLERY_COST = 35
NDefines.NMilitary.DEFAULT_WARGOAL_BATTLESCORE_BONUS = 2.5

NDefines.NGovernment.MAMLUK_RECRUIT_MANPOWER_MULTIPLIER = 1
